### PR TITLE
Fixed selecting yellow server on saved accounts

### PR DESCRIPTION
**Pull request by ghost**
Sorry for all the commits just to make 1 single edit, I still struggle to manage my branches and when they are local and when I push where am I pushing and whatnot.

### CODE REVIEW

**Comment by Yecinan** [comment]
Hello, I have a question, after clone or download your repository, how to run proshine, cause i cant find proshine.exe like when i download from http://proshine-bot.ml/. Sorry for commenting here because i cant find any way to contact you. :)

**Comment by ghost** [comment]
You only clone or download the repository if you can build or compile the latest features, if you don't know how to do that I suggest you to go to [my releases](https://github.com/Emuuung/proshine/releases) for a full functioning software of Proshine.

**Comment by Yecinan** [comment]
If u dont mind can u tell me how to build from the project. :D I want to add or modified some function myself. I tried to open .dll file but it seems i cant edit it. :/

**Comment by ghost** [comment]
For that I suggest you use Visual Basic, you can download the free version, Then download the plugin for Github and add your own repository where you can test and debug, and ultimately build it.

**Comment by Yecinan** [comment]
Ok, thanks you so much. I prefer using Sublime text. :D But can u teach me to build the program after i modify some files plz. I never buy a pc program be4.

**Comment by ghost** [comment]
Please ask for assistance in the Proshine forums.

**Comment by Yecinan** [comment]
ok, thank you so much for helping me. :+1:

**Pull request closed without merging**
