### PR TITLE
Added API: Pokedex

### PR DESCRIPTION
**Pull request by Rympex**
getPokedexOwned()
getPokedexSeen()
getPokedexEvolved()

### CODE REVIEW

**Comment by ghost** [comment]
Theres an issue here, no matter how many pokemon I catch when I try to start [https://github.com/g0ldPRO/Questing.lua/pull/22/files](url) it always say:
- `Error during the script execution: Quests/Kanto/HmFlashQuest.lua:(42,8-118): To take [HM05 - Flash] need 10 pokemons, you still have to catch 10 pokemons`

**Comment by Rympex** [comment]
i got no errors, and 1 other guy on discord, don't have this problem

Try add again this APIs:
the script work nice, i already test start to fuchsia city without problem

**Comment by ghost** [comment]
That's weird, is it possible that `Bot.Game.Pokedex_Owned` needs to be defined?
I think it just returns 0 when using the `getPokedexOwned()` function cause the above variable is not expressed.

**Comment by Rympex** [comment]
Yes Fixed, Missing:

Pokedex_Owned = Convert.ToInt32(playerData[4]);
Pokedex_Seen = Convert.ToInt32(playerData[5]);
Pokedex_Evolved = Convert.ToInt32(playerData[6]);

**Comment by ghost** [comment]
That worked very nicely, thank you so much!
Edit: tested it all and worked.

**Pull request merged**
