### PR TITLE
Add hasItemID

### PR DESCRIPTION
**Pull request by tndh**
// API: hasItem ID and get Item quantity ID

### CODE REVIEW

**Comment by Zonz** [comment]
Why would you need this?

**Comment by tndh** [comment]
try hasItem("HM03 - Fly"),it not work

**Comment by Zonz** [comment]
Fly is Hm 2. hasItem("HM02 - Fly") works just fine.

**Comment by Silv3rPRO** [comment]
I don't thing this function is required, but it works and doesn't cost anything to add.
Thanks!

**Pull request merged**
